# see
# https://www.apollographql.com/docs/router/configuration/overview#yaml-config-file
# https://www.apollographql.com/docs/router/configuration/health-checks
# https://www.apollographql.com/docs/router/configuration/tracing
#
health-check:
  listen: 0.0.0.0:8088
  enabled: true
supergraph:
  # The socket address and port to listen on
  listen: 0.0.0.0:4000
cors:
  allow_any_origin: true
telemetry:
  metrics:
    common:
      resources:
        service.name: release-name-router
    prometheus:
      enabled: true
      listen: 127.0.0.1:9090
      path: /metrics

# --------------------
# note: `router --dev` has these default settings and enables the --hot-reload flag
# --------------------
# supergraph:
#   introspection: true
# sandbox:
#   enabled: true
# homepage:
#   enabled: false
# include_subgraph_errors:
#   all: true # Propagate errors from all subgraphs
# plugins:
#   experimental.expose_query_plan: true
