apiVersion: v1
kind: ServiceAccount
metadata:
  name: router
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-deployment
  labels:
    app: router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      serviceAccountName: router
      securityContext:
        {}      
      containers:
        - name: router
          image: ghcr.io/apollographql/router:v1.29.1
          imagePullPolicy: IfNotPresent
          # startup option: https://www.apollographql.com/docs/router/managed-federation/setup#3-modify-your-apollo-router-startup-if-necessary
          args:
            - --dev
            - --hot-reload
            - --config
            - /etc/config/router-config.yaml
            - --supergraph
            - /etc/config/supergraph.graphql
            - --log
            - info
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
            - name: health
              containerPort: 8088
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8088
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8088
          volumeMounts:
          - name: routerconfig-volume
            mountPath: /etc/config
            readOnly: true
      volumes:
        - name: routerconfig-volume
          configMap:
            name: routerconfig
---
apiVersion: v1
kind: Service
metadata:
  name: router-service
spec:
  selector:
    app: router
  ports:
    - port: 4000
      targetPort: http
      protocol: TCP
      name: http
    - port: 8088
      targetPort: health
      protocol: TCP
      name: health
